matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover

    - language: csharp
      solution: SeparatedConserns\SeparatedConserns.sln

    

notifications:
  email:
    - mail@christopher-elliott.com