matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover

    # - language: csharp
    #   solution: SeparatedConcerns/SeparatedConcerns.sln

    - language: ghc
      ghc:
        - "8.2"
      before_script:
        - cd haskell
      script:
        # - cabal install --only-dependencies --enable-tests
        - cabal configure --enable-tests && cabal build && cabal test


    - language: rust
      before_script:
        - cd Rust
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all