matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover

    - language: csharp
      solution: csharp/SeparatedConcerns.sln

    - language: rust
      before_script:
        - cd rust
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
    

notifications:
  email:
    - mail@christopher-elliott.com