matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest discover

    - language: csharp
      solution: SeparatedConcerns/SeparatedConcerns.sln

    

notifications:
  email:
    - mail@christopher-elliott.com